<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.client</package>
    <name>CustomResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.client.CustomResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.client.CustomResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.custom.client.CustomResource</className>
    <resourceItems>
        <resourceItem>
            <name>UIToolQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.client.CustomResource].resourceItems.resourceItem[UIToolQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>YzjAuditLogQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.client.CustomResource].resourceItems.resourceItem[YzjAuditLogQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>WebAuditLogQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.client.CustomResource].resourceItems.resourceItem[WebAuditLogQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ProjectToTakeOverQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.client.CustomResource].resourceItems.resourceItem[ProjectToTakeOverQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementLedgerInputQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.client.CustomResource].resourceItems.resourceItem[SettlementLedgerInputQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BodstandQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.client.CustomResource].resourceItems.resourceItem[BodstandQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SyncEmpLogQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.client.CustomResource].resourceItems.resourceItem[SyncEmpLogQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>TaskQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.client.CustomResource].resourceItems.resourceItem[TaskQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>EmpAttendQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.client.CustomResource].resourceItems.resourceItem[EmpAttendQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>TextQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.client.CustomResource].resourceItems.resourceItem[TextQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.client.CustomResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.client.CustomResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.client.CustomResource].resourceItems.resourceItem[BodstandQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="预算台账" />
            <lang locale="zh_HK" value="預算台賬" />
            <lang locale="zh_TW" value="預算台賬" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.client.CustomResource].resourceItems.resourceItem[EmpAttendQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="员工考勤信息" />
            <lang locale="zh_HK" value="員工考勤信息" />
            <lang locale="zh_TW" value="員工考勤信息" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.client.CustomResource].resourceItems.resourceItem[ProjectToTakeOverQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="项目对接人" />
            <lang locale="zh_HK" value="項目對接人" />
            <lang locale="zh_TW" value="項目對接人" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.client.CustomResource].resourceItems.resourceItem[SettlementLedgerInputQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="结算台账录入" />
            <lang locale="zh_HK" value="結算台賬錄入" />
            <lang locale="zh_TW" value="結算台賬錄入" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.client.CustomResource].resourceItems.resourceItem[SyncEmpLogQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="人员同步日志" />
            <lang locale="zh_HK" value="人員同步日誌" />
            <lang locale="zh_TW" value="人員同步日誌" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.client.CustomResource].resourceItems.resourceItem[TaskQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="消息" />
            <lang locale="zh_HK" value="消息" />
            <lang locale="zh_TW" value="消息" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.client.CustomResource].resourceItems.resourceItem[TextQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="测试" />
            <lang locale="zh_HK" value="測試" />
            <lang locale="zh_TW" value="測試" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.client.CustomResource].resourceItems.resourceItem[UIToolQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="UI工具" />
            <lang locale="zh_HK" value="UI工具" />
            <lang locale="zh_TW" value="UI工具" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.client.CustomResource].resourceItems.resourceItem[WebAuditLogQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="web审批日志" />
            <lang locale="zh_HK" value="web審批日誌" />
            <lang locale="zh_TW" value="web審批日誌" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.client.CustomResource].resourceItems.resourceItem[YzjAuditLogQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="web审批日志记录" />
            <lang locale="zh_HK" value="web審批日誌記錄" />
            <lang locale="zh_TW" value="web審批日誌記錄" />
        </rs>
    </resource>
</i18nResource>

